# Generated by Django 4.1.2 on 2022-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('time_1h', models.CharField(max_length=50)),
                ('time_24h', models.CharField(max_length=50)),
                ('time_7d', models.CharField(max_length=50)),
                ('market_cap', models.CharField(max_length=50)),
                ('volume_by_price', models.CharField(max_length=50)),
                ('volume_by_units', models.CharField(max_length=50)),
                ('supply', models.CharField(max_length=60)),
            ],
        ),
    ]
